// Emoji to word mappings
export const emojiToWord = {
  '😀': 'grinning',
  '😃': 'smile',
  '😄': 'happy',
  '😁': 'grin',
  '😆': 'laughing',
  '😅': 'sweat smile',
  '🤣': 'rolling on the floor laughing',
  '😂': 'tears of joy',
  '🙂': 'slightly smiling',
  '🙃': 'upside down',
  '😉': 'wink',
  '😊': 'blush',
  '😇': 'angel',
  '🥰': 'hearts',
  '😍': 'heart eyes',
  '🤩': 'star struck',
  '😘': 'kiss',
  '😗': 'kissing',
  '😚': 'kissing closed eyes',
  '😙': 'kissing smiling eyes',
  '🥲': 'tears of joy',
  '😋': 'yum',
  '😛': 'tongue out',
  '😜': 'winking tongue',
  '🤪': 'crazy',
  '😝': 'squinting tongue',
  '🤑': 'money mouth',
  '🤗': 'hugging',
  '🤭': 'hand over mouth',
  '🤫': 'shushing',
  '🤔': 'thinking',
  '🤐': 'zipper mouth',
  '🤨': 'raised eyebrow',
  '😐': 'neutral',
  '😑': 'expressionless',
  '😶': 'no mouth',
  '😏': 'smirk',
  '😒': 'unamused',
  '🙄': 'eye roll',
  '😬': 'grimacing',
  '🤥': 'lying',
  '😌': 'relieved',
  '😔': 'pensive',
  '😪': 'sleepy',
  '🤤': 'drooling',
  '😴': 'sleeping',
  '😷': 'mask',
  '🤒': 'sick',
  '🤕': 'bandage',
  '🤢': 'nauseated',
  '🤮': 'vomiting',
  '🤧': 'sneezing',
  '🥵': 'hot',
  '🥶': 'cold',
  '🥴': 'dizzy',
  '😵': 'dizzy face',
  '🤯': 'mind blown',
  '🤠': 'cowboy',
  '🥳': 'party',
  '🥸': 'disguise',
  '😎': 'cool',
  '🤓': 'nerd',
  '🧐': 'monocle',
  '😕': 'confused',
  '😟': 'worried',
  '🙁': 'frown',
  '☹️': 'frowning',
  '😮': 'wow',
  '😯': 'surprised',
  '😲': 'astonished',
  '😳': 'flushed',
  '🥺': 'pleading',
  '😦': 'frowning mouth',
  '😧': 'anguished',
  '😨': 'fearful',
  '😰': 'anxious sweat',
  '😥': 'sad sweat',
  '😢': 'crying',
  '😭': 'sobbing',
  '😱': 'screaming',
  '😖': 'confounded',
  '😣': 'persevering',
  '😞': 'disappointed',
  '😓': 'downcast sweat',
  '😩': 'weary',
  '😫': 'tired',
  '🥱': 'yawning',
  '😤': 'triumph',
  '😡': 'angry',
  '😠': 'rage',
  '🤬': 'cursing',
  '😈': 'devil',
  '👿': 'angry devil',
  '💀': 'skull',
  '☠️': 'skull and crossbones',
  '💩': 'poop',
  '🤡': 'clown',
  '👹': 'ogre',
  '👺': 'goblin',
  '👻': 'ghost',
  '👽': 'alien',
  '👾': 'space invader',
  '🤖': 'robot',
  '😺': 'cat smile',
  '😸': 'cat grin',
  '😹': 'cat tears of joy',
  '😻': 'cat heart eyes',
  '😼': 'cat smirk',
  '😽': 'cat kiss',
  '🙀': 'cat scream',
  '😿': 'cat crying',
  '😾': 'cat pouting',
  '❤️': 'red heart',
  '🧡': 'orange heart',
  '💛': 'yellow heart',
  '💚': 'green heart',
  '💙': 'blue heart',
  '💜': 'purple heart',
  '🖤': 'black heart',
  '🤍': 'white heart',
  '🤎': 'brown heart',
  '💔': 'broken heart',
  '❣️': 'heart exclamation',
  '💕': 'two hearts',
  '💞': 'revolving hearts',
  '💓': 'beating heart',
  '💗': 'growing heart',
  '💖': 'sparkling heart',
  '💘': 'cupid heart',
  '💝': 'heart box',
  '💟': 'heart decoration',
  '☮️': 'peace',
  '✝️': 'cross',
  '☪️': 'star and crescent',
  '🕉️': 'om',
  '☸️': 'dharma wheel',
  '✡️': 'star of david',
  '🔯': 'six pointed star',
  '🕎': 'menorah',
  '☯️': 'yin yang',
  '☦️': 'orthodox cross',
  '🛐': 'place of worship',
  '⛎': 'ophiuchus',
  '♈': 'aries',
  '♉': 'taurus',
  '♊': 'gemini',
  '♋': 'cancer',
  '♌': 'leo',
  '♍': 'virgo',
  '♎': 'libra',
  '♏': 'scorpio',
  '♐': 'sagittarius',
  '♑': 'capricorn',
  '♒': 'aquarius',
  '♓': 'pisces',
  '🆔': 'id',
  '⚛️': 'atom',
  '🉑': 'accept',
  '☢️': 'radioactive',
  '☣️': 'biohazard',
  '📴': 'mobile off',
  '📳': 'vibration',
  '🈶': 'not free',
  '🈚': 'free',
  '🈸': 'application',
  '🈺': 'open for business',
  '🈷️': 'monthly',
  '✴️': 'eight pointed star',
  '🆚': 'versus',
  '💮': 'white flower',
  '🉐': 'bargain',
  '㊙️': 'secret',
  '㊗️': 'congratulations',
  '🈴': 'passing grade',
  '🈵': 'no vacancy',
  '🈹': 'discount',
  '🈲': 'prohibited',
  '🅰️': 'a button',
  '🅱️': 'b button',
  '🆎': 'ab button',
  '🆑': 'cl button',
  '🅾️': 'o button',
  '🆘': 'sos',
  '❌': 'cross mark',
  '⭕': 'circle',
  '🛑': 'stop',
  '⛔': 'no entry',
  '📛': 'name badge',
  '🚫': 'prohibited',
  '💯': 'hundred',
  '💢': 'anger',
  '♨️': 'hot springs',
  '🚷': 'no pedestrians',
  '🚯': 'no littering',
  '🚳': 'no bicycles',
  '🚱': 'non potable water',
  '🔞': 'underage',
  '📵': 'no mobile',
  '🚭': 'no smoking',
  '❗': 'exclamation',
  '❕': 'exclamation mark',
  '❓': 'question',
  '❔': 'question mark',
  '‼️': 'double exclamation',
  '⁉️': 'question exclamation',
  '🔅': 'dim',
  '🔆': 'bright',
  '〽️': 'part alternation',
  '⚠️': 'warning',
  '🚸': 'children crossing',
  '🔱': 'trident',
  '⚜️': 'fleur de lis',
  '🔰': 'beginner',
  '♻️': 'recycling',
  '✅': 'check mark',
  '🈯': 'reserved',
  '💹': 'chart increasing',
  '❇️': 'sparkle',
  '✳️': 'eight spoked asterisk',
  '❎': 'cross mark button',
  '🌐': 'globe',
  '💠': 'diamond shape',
  'Ⓜ️': 'metro',
  '🌀': 'cyclone',
  '💤': 'zzz',
  '🏧': 'atm',
  '🚾': 'water closet',
  '♿': 'wheelchair',
  '🅿️': 'parking',
  '🈳': 'vacancy',
  '🈂️': 'service charge',
  '🛂': 'passport control',
  '🛃': 'customs',
  '🛄': 'baggage claim',
  '🛅': 'left luggage',
  '🚹': 'men',
  '🚺': 'women',
  '🚼': 'baby',
  '⚧️': 'transgender',
  '🚻': 'restroom',
  '🚮': 'litter',
  '🎦': 'cinema',
  '📶': 'signal',
  '🈁': 'here',
  '🔣': 'symbols',
  'ℹ️': 'information',
  '🔤': 'abc',
  '🔡': 'abcd',
  '🔠': 'capitals',
  '🆖': 'ng',
  '🆗': 'ok',
  '🆙': 'up',
  '🆒': 'cool',
  '🆕': 'new',
  '🆓': 'free',
  '0️⃣': 'zero',
  '1️⃣': 'one',
  '2️⃣': 'two',
  '3️⃣': 'three',
  '4️⃣': 'four',
  '5️⃣': 'five',
  '6️⃣': 'six',
  '7️⃣': 'seven',
  '8️⃣': 'eight',
  '9️⃣': 'nine',
  '🔟': 'ten',
  '👍': 'thumbs up',
  '👎': 'thumbs down',
  '👋': 'wave',
  '🤚': 'raised hand',
  '🖐️': 'hand with fingers',
  '✋': 'raised hand',
  '🖖': 'vulcan salute',
  '👌': 'ok hand',
  '🤌': 'pinched fingers',
  '🤏': 'pinching hand',
  '✌️': 'peace',
  '🤞': 'crossed fingers',
  '🤟': 'love you',
  '🤘': 'rock on',
  '🤙': 'call me',
  '👈': 'backhand left',
  '👉': 'backhand right',
  '👆': 'backhand up',
  '🖕': 'middle finger',
  '👇': 'backhand down',
  '☝️': 'index up',
  '✊': 'raised fist',
  '👊': 'fist bump',
  '🤛': 'left fist',
  '🤜': 'right fist',
  '👏': 'clapping',
  '🙌': 'raising hands',
  '👐': 'open hands',
  '🤲': 'palms together',
  '🤝': 'handshake',
  '🙏': 'pray',
  '✍️': 'writing',
  '💅': 'nail polish',
  '🤳': 'selfie',
  '💪': 'muscle',
  '🦾': 'mechanical arm',
  '🦿': 'mechanical leg',
  '🦵': 'leg',
  '🦶': 'foot',
  '👂': 'ear',
  '🦻': 'ear with hearing aid',
  '👃': 'nose',
  '🧠': 'brain',
  '🫀': 'anatomical heart',
  '🫁': 'lungs',
  '🦷': 'tooth',
  '🦴': 'bone',
  '👀': 'eyes',
  '👁️': 'eye',
  '👅': 'tongue',
  '👄': 'mouth',
  '🔥': 'fire',
  '💧': 'droplet',
  '💦': 'sweat droplets',
  '🌊': 'wave',
  '🎉': 'party popper',
  '🎊': 'confetti',
  '🎈': 'balloon',
  '🎁': 'gift',
  '🏆': 'trophy',
  '🥇': 'gold medal',
  '🥈': 'silver medal',
  '🥉': 'bronze medal',
  '⚽': 'soccer ball',
  '⚾': 'baseball',
  '🥎': 'softball',
  '🏀': 'basketball',
  '🏐': 'volleyball',
  '🏈': 'football',
  '🏉': 'rugby',
  '🎾': 'tennis',
  '🥏': 'flying disc',
  '🎳': 'bowling',
  '🏏': 'cricket',
  '🏑': 'field hockey',
  '🏒': 'ice hockey',
  '🥍': 'lacrosse',
  '🏓': 'ping pong',
  '🏸': 'badminton',
  '🥊': 'boxing glove',
  '🥋': 'martial arts',
  '🥅': 'goal',
  '⛳': 'flag in hole',
  '⛸️': 'ice skate',
  '🎣': 'fishing pole',
  '🤿': 'diving mask',
  '🎽': 'running shirt',
  '🎿': 'skis',
  '🛷': 'sled',
  '🥌': 'curling stone',
  '🎯': 'bullseye',
  '🪀': 'yo-yo',
  '🪁': 'kite',
  '🎱': 'pool ball',
  '🔮': 'crystal ball',
  '🪄': 'magic wand',
  '🧿': 'nazar amulet',
  '🎮': 'video game',
  '🕹️': 'joystick',
  '🎰': 'slot machine',
  '🎲': 'dice',
  '🧩': 'puzzle piece',
  '🧸': 'teddy bear',
  '🪅': 'pinata',
  '🪆': 'nesting dolls',
  '♠️': 'spade',
  '♥️': 'heart suit',
  '♦️': 'diamond suit',
  '♣️': 'club suit',
  '♟️': 'chess pawn',
  '🃏': 'joker',
  '🀄': 'mahjong',
  '🎴': 'flower cards',
  '🎭': 'performing arts',
  '🖼️': 'framed picture',
  '🎨': 'artist palette',
  '🧵': 'thread',
  '🪡': 'sewing needle',
  '🧶': 'yarn',
  '🪢': 'knot',
  '🍕': 'pizza',
  '🍔': 'burger',
  '🍟': 'fries',
  '🌭': 'hot dog',
  '🍿': 'popcorn',
  '🧈': 'butter',
  '🧂': 'salt',
  '🥚': 'egg',
  '🍳': 'cooking',
  '🧇': 'waffle',
  '🥞': 'pancakes',
  '🧀': 'cheese',
  '🍖': 'meat',
  '🍗': 'poultry',
  '🥩': 'steak',
  '🥓': 'bacon',
  '🌮': 'taco',
  '🌯': 'burrito',
  '🥙': 'stuffed flatbread',
  '🥘': 'paella',
  '🍲': 'pot of food',
  '🥣': 'bowl with spoon',
  '🥗': 'salad',
  '🥫': 'canned food',
  '🍱': 'bento',
  '🍘': 'rice cracker',
  '🍙': 'rice ball',
  '🍚': 'cooked rice',
  '🍛': 'curry',
  '🍜': 'steaming bowl',
  '🍝': 'spaghetti',
  '🍠': 'roasted sweet potato',
  '🍢': 'oden',
  '🍣': 'sushi',
  '🍤': 'fried shrimp',
  '🍥': 'fish cake',
  '🥮': 'moon cake',
  '🍡': 'dango',
  '🥟': 'dumpling',
  '🥠': 'fortune cookie',
  '🥡': 'takeout box',
  '🦀': 'crab',
  '🦞': 'lobster',
  '🦐': 'shrimp',
  '🦑': 'squid',
  '🦪': 'oyster',
  '🍦': 'ice cream',
  '🍧': 'shaved ice',
  '🍨': 'ice cream',
  '🍩': 'donut',
  '🍪': 'cookie',
  '🎂': 'birthday cake',
  '🍰': 'cake',
  '🧁': 'cupcake',
  '🥧': 'pie',
  '🍫': 'chocolate',
  '🍬': 'candy',
  '🍭': 'lollipop',
  '🍮': 'custard',
  '🍯': 'honey',
  '🍼': 'baby bottle',
  '🥛': 'milk',
  '☕': 'coffee',
  '🫖': 'teapot',
  '🍵': 'tea',
  '🍶': 'sake',
  '🍾': 'champagne',
  '🍷': 'wine',
  '🍸': 'cocktail',
  '🍹': 'tropical drink',
  '🍺': 'beer',
  '🍻': 'beers',
  '🥂': 'clinking glasses',
  '🥃': 'tumbler',
  '🥤': 'cup with straw',
  '🧋': 'bubble tea',
  '🧃': 'juice box',
  '🧉': 'mate',
  '🧊': 'ice',
};

// Create reverse mapping (word to emoji)
export const wordToEmoji = Object.entries(emojiToWord).reduce(
  (acc, [emoji, word]) => {
    acc[word.toLowerCase()] = emoji;
    return acc;
  },
  {}
);

// Translate text to emojis
export const translateToEmojis = (text) => {
  if (!text.trim()) return '';
  
  const words = text.toLowerCase().split(/\s+/);
  const result = [];
  let i = 0;
  
  while (i < words.length) {
    let matched = false;
    
    // Try to match phrases of decreasing length (3 words, 2 words, 1 word)
    for (let phraseLength = Math.min(3, words.length - i); phraseLength >= 1; phraseLength--) {
      const phrase = words.slice(i, i + phraseLength).join(' ');
      const cleanPhrase = phrase.replace(/[.,!?;:]$/, '');
      const punctuation = phrase.match(/[.,!?;:]$/) || [''];
      
      if (wordToEmoji[cleanPhrase]) {
        result.push(wordToEmoji[cleanPhrase] + punctuation[0]);
        i += phraseLength;
        matched = true;
        break;
      }
    }
    
    if (!matched) {
      // No emoji found, keep original word
      result.push(words[i]);
      i++;
    }
  }
  
  return result.join(' ');
};

// Translate emojis to text
export const translateToWords = (text) => {
  if (!text.trim()) return '';
  
  // Match emojis using regex
  const emojiRegex = /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/gu;
  
  return text.replace(emojiRegex, (emoji) => {
    return emojiToWord[emoji] ? ` ${emojiToWord[emoji]} ` : emoji;
  }).replace(/\s+/g, ' ').trim();
};
